algoritz_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('trade.urls', namespace='trade')),
]

trade/urls.py
from django.urls import path


from .apps import TradeConfig
from .views import request_data_view, AlgoDataListView, AlgoChartJSONView, AlgoDataDetailView


app_name = TradeConfig.name


urlpatterns = [
    path('', request_data_view, name='request_data'),
    path('list/', AlgoDataListView.as_view(), name='algos_list'),
    path('detail/<int:pk>/', AlgoDataDetailView.as_view(), name='algo_detail'),
    path('chart_data/<int:pk>/', AlgoChartJSONView.as_view(), name='algo_chart')
]

trade/models.py
import json
import numpy

from django.db import models

# Create your models here.


class RequestedAlgoData(models.Model):
    """
    Model for store requested algo data
    """
    name = models.CharField(max_length=255)
    ticker = models.CharField(max_length=255)
    pnl = models.TextField()
    positions = models.TextField()

    def _get_text_field_as_json(self, values):
        return json.loads(values)

    def get_pnl_as_python(self):
        return self._get_text_field_as_json(self.pnl)

    def get_positions_as_python(self):
        return self._get_text_field_as_json(self.positions)

    @property
    def avg_pnl(self):
        return numpy.mean(self.get_pnl_as_python())

trade/forms.py
from django import forms


class RequestAlgoData(forms.Form):
    """
    Request algo data form
    """
    algo_name = forms.CharField(max_length=255, label='Algo name')
    signal = forms.CharField(max_length=120, label='Signal')
    trade = forms.CharField(max_length=120, label='Trade')
    ticker = forms.CharField(max_length=80, label='Ticker')

trade/views.py
import json

from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from chartjs.views.lines import BaseLineChartView

from .forms import RequestAlgoData
from .core.api_functions import get_prices
from .core.algo_functions import algo_result
from .models import RequestedAlgoData

# Create your views here.


def request_data_view(request):
    """
    Show and handle form for request algo data
    """
    if request.method == 'GET':
        form = RequestAlgoData()
        return render(request, 'request_algo_data.html', {'form': form})
    if request.method == 'POST':
        form = RequestAlgoData(request.POST)
        if form.is_valid():
            ticker = form.cleaned_data['ticker']
            signal = form.cleaned_data['signal']
            trade = form.cleaned_data['trade']
            prices = get_prices(ticker)
            try:
                [positions, PnL] = algo_result(signal, trade, prices)
                algo_data = RequestedAlgoData()
                algo_data.name = form.cleaned_data['algo_name']
                algo_data.ticker = ticker
                algo_data.positions = json.dumps(positions)
                algo_data.pnl = json.dumps(PnL)
                algo_data.save()
                messages.add_message(request, messages.SUCCESS,
                                     'Algo data for {} requested and saved'.format(algo_data.name))
            except SystemExit:
                messages.add_message(request, messages.ERROR, 'Could not process data with this params')
        return render(request, 'request_algo_data.html', {'form': form})


class AlgoDataListView(ListView):
    """
    Show saved algos list
    """
    template_name = 'list_algo_data.html'
    queryset = RequestedAlgoData.objects.all()


class AlgoDataDetailView(DetailView):
    """
    Show charts for selected algo
    """
    template_name = 'detail_algo_data.html'
    queryset = RequestedAlgoData.objects.all()


class AlgoChartJSONView(BaseLineChartView):
    """
    Get data for selected algo
    """
    def dispatch(self, request, *args, **kwargs):
        self.algo = get_object_or_404(RequestedAlgoData, pk=kwargs.get('pk'))
        return super(AlgoChartJSONView, self).dispatch(request, *args, **kwargs)

    def get_labels(self):
        return self.algo.get_positions_as_python()

    def get_providers(self):
        return [self.algo.name]

    def get_data(self):
        return [self.algo.get_pnl_as_python()]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
    <div>
        {% for message in messages %}
                <p style="color:  {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}alert-danger{% else %}alert-success{% endif %}">
                    {{  message }}
                </p>
        {% endfor %}
    </div>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
    {% block body_scripts %}
    {% endblock %}
</body>
</html>

trade/templates/detail_algo_data.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Data for {{ object.name }}{% endblock %}
{% block content %}
        <h1>{{ object.name }}!</h1>

        <canvas id="algoChart" width="500" height="400"></canvas>
{% endblock %}
{% block body_scripts %}
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
        <script type="text/javascript" src="{% static 'js/Chart.min.js' %}"></script>
        <script type="text/javascript">
            $.get('{% url "trade:algo_chart" object.pk %}', function(data) {
                var ctx = $("#algoChart").get(0).getContext("2d");
                new Chart(ctx, {
                    type: 'line', data: data
                });
            });
        </script>
{% endblock %}

trade/templates/list_algo_data.html
{% extends "base.html" %}
{% block title %}Saved algos{% endblock %}
{% block content %}
    <h1>Saved algo</h1>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Avg. PnL
                </th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object_list %}
                <tr>
                    <td>
                        <a href="{% url 'trade:algo_detail' obj.pk %}">
                            {{ obj.name }}
                        </a>
                    </td>
                    <td>
                        {{ obj.avg_pnl }}
                    </td>
                </tr>
             {% empty %}
                <tr>
                    <td colspan="2">
                        No algos yet
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

trade/templates/request_algo_data.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Request data{% endblock %}
{% block content %}
    <h1>Request algo</h1>
    <form action="." method="post">
        {% csrf_token %}
        {{ form| crispy }}
        <button type="submit" class="btn btn-primary">Request data</button>
    </form>
    <p class="text-center">
        <a href="{% url 'trade:algos_list' %}" class="btn btn-success">View all algos</a>
    </p>
{% endblock %}